-- ============================================================
-- STEP 1 : Setup de l'environnement
-- ============================================================

-- 1. Warehouse dédié au projet
CREATE WAREHOUSE IF NOT EXISTS ELT_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse principal du projet ELT NYC Taxi';

-- 2. Database principale
CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB
  COMMENT = 'Projet ELT - NYC TLC Trip Records';

-- 3. Schémas Medallion
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.BRONZE
  COMMENT = 'Données brutes ingérées sans transformation';

CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.SILVER
  COMMENT = 'Données nettoyées et typées';

CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.GOLD
  COMMENT = 'Agrégats et métriques business';

CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.STAGING
  COMMENT = 'Stages et file formats';

-- 4. Rôles RBAC
CREATE ROLE IF NOT EXISTS ELT_ENGINEER
  COMMENT = 'Accès complet au pipeline ELT';

CREATE ROLE IF NOT EXISTS ELT_ANALYST
  COMMENT = 'Lecture seule sur la couche Gold';

-- Privilèges ELT_ENGINEER
GRANT USAGE ON WAREHOUSE ELT_WH TO ROLE ELT_ENGINEER;
GRANT ALL ON DATABASE NYC_TAXI_DB TO ROLE ELT_ENGINEER;
GRANT ALL ON ALL SCHEMAS IN DATABASE NYC_TAXI_DB TO ROLE ELT_ENGINEER;

-- Privilèges ELT_ANALYST
GRANT USAGE ON WAREHOUSE ELT_WH TO ROLE ELT_ANALYST;
GRANT USAGE ON DATABASE NYC_TAXI_DB TO ROLE ELT_ANALYST;
GRANT USAGE ON SCHEMA NYC_TAXI_DB.GOLD TO ROLE ELT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_DB.GOLD TO ROLE ELT_ANALYST;

-- Assigner les rôles à ton user
GRANT ROLE ELT_ENGINEER TO USER GAUTIER;
GRANT ROLE ELT_ANALYST TO USER GAUTIER;

-- 5. Vérification
SHOW WAREHOUSES LIKE 'ELT_WH';
SHOW DATABASES LIKE 'NYC_TAXI_DB';
SHOW SCHEMAS IN DATABASE NYC_TAXI_DB;

